name:                exercise
version:             0.1.0.0
github:              "dktsudgg/study-haskell"
license:             BSD3
author:              "dktsudgg"
maintainer:          "dktsudgg@gmail.com"
copyright:           "2022 dktsudgg"

extra-source-files:
- README.md
- ChangeLog.md

# Metadata used when publishing your package
# synopsis:            Short description of your package
# category:            Web

# To avoid duplicated efforts in documentation and dealing with the
# complications of embedding Haddock markup inside cabal files, it is
# common to point users to the README.md file.
description:         Please see the README on GitHub at <https://github.com/dktsudgg/study-haskell/#readme>

dependencies:
- base >= 4.7 && < 5
- ansi-terminal # for using "System.Console.ANSI". found from google "stackage System.Console.ANSI"
- gi-harfbuzz == 0.0.6 # https://github.com/haskell-gi/haskell-gi/issues/385
- gi-gtk
- haskell-gi-base

library:
  source-dirs:
  - src
  - src/chapters/Chapter8
  - src/chapters/Chapter9

executables:
  exercise-exe:
    main:                Main.hs
    source-dirs:         app
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - exercise

tests:
  exercise-test:
    main:                Spec.hs
    source-dirs:         test
    ghc-options:
    - -threaded
    - -rtsopts
    - -with-rtsopts=-N
    dependencies:
    - exercise
